// // https://www.freetogame.com/api/games

const grid = document.querySelector('.grid');
console.log(grid);
(async () => {
	try {
		const {data} = await axios.get("/api/game");
     console.log(data);

	} catch (error) {
		// window.location.pathname = "/login";
		console.log(error);
	}
})();

const dataGames = [ 
	{
	id: 560,
	title: 'Palia',
	thumbnail: 'https://www.freetogame.com/g/560/thumbnail.jpg',
	short_description: 'A cozy MMO with homebuilding and some adventure.',
	game_url: 'https://www.freetogame.com/open/palia',
	genre: 'MMORPG',
	platform: 'PC (Windows)',
	publisher: 'Singularity Six',
	developer: 'Singularity Six',
	release_date: '2023-08-10',
	freetogame_profile_url: 'https://www.freetogame.com/palia'
  },
  {
	id: 458,
	title: "League of Angels - Heaven's Fury",
	thumbnail: 'https://www.freetogame.com/g/458/thumbnail.jpg',
	short_description: 'A free-to-play, browser-based fantasy online action RPG based loosely on Western mythology!',
	game_url: 'https://www.freetogame.com/open/league-of-angels-heavens-fury',
	genre: 'MMORPG',
	platform: 'Web Browser',
	publisher: 'Gtarcade',
	developer: 'Yoozoo Games',
	release_date: '2020-01-09',
	freetogame_profile_url: 'https://www.freetogame.com/league-of-angels-heavens-fury'
  },
  {
	id: 14,
	title: 'Star Trek Online',
	thumbnail: 'https://www.freetogame.com/g/14/thumbnail.jpg',
	short_description: 'A free-to-play, 3D, Sci-Fi MMORPG based on the popular Star Trek series.',
	game_url: 'https://www.freetogame.com/open/star-trek-online',
	genre: 'MMORPG',
	platform: 'PC (Windows)',
	publisher: 'Perfect World Entertainment',
	developer: ' Cryptic Studios',
	release_date: '2010-02-02',
	freetogame_profile_url: 'https://www.freetogame.com/star-trek-online'
  },
  {
	id: 595,
	title: 'Brighter Shores',
	thumbnail: 'https://www.freetogame.com/g/595/thumbnail.jpg',
	short_description: "A point-and-click MMORPG from RuneScape's creator, Andrew Gower.",
	game_url: 'https://www.freetogame.com/open/brighter-shores',
	genre: 'MMORPG',
	platform: 'PC (Windows)',
	publisher: 'Fen Research LTD',
	developer: 'Fen Research LTD',
	release_date: '2024-11-06',
	freetogame_profile_url: 'https://www.freetogame.com/brighter-shores'
  },
  {
	id: 529,
	title: 'Tower of Fantasy',
	thumbnail: 'https://www.freetogame.com/g/529/thumbnail.jpg',
	short_description: 'Tower of Fantasy is a 3D open-world RPG, anime-style sci-fi MMO RPG game with unique characters and beautiful open vistas!',
	game_url: 'https://www.freetogame.com/open/tower-of-fantasy',
	genre: 'MMORPG',
	platform: 'PC (Windows)',
	publisher: 'Level Infinite',
	developer: 'Hotta Studio',
	release_date: '2022-08-10',
	freetogame_profile_url: 'https://www.freetogame.com/tower-of-fantasy'
  },
  {
	id: 515,
	title: 'Halo Infinite',
	thumbnail: 'https://www.freetogame.com/g/515/thumbnail.jpg',
	short_description: 'For the first time ever, a free-to-play Halo experience is available in the form of Halo Infinite’s multiplayer.',
	game_url: 'https://www.freetogame.com/open/halo-infinite',
	genre: 'Shooter',
	platform: 'PC (Windows)',
	publisher: 'Xbox Game Studios',
	developer: '343 Industries',
	release_date: '2021-11-15',
	freetogame_profile_url: 'https://www.freetogame.com/halo-infinite'
  },
  {
	id: 466,
	title: 'Valorant',
	thumbnail: 'https://www.freetogame.com/g/466/thumbnail.jpg',
	short_description: 'Test your mettle in Riot Games’ character-based FPS shooter Valorant.',
	game_url: 'https://www.freetogame.com/open/valorant',
	genre: 'Shooter',
	platform: 'PC (Windows)',
	publisher: 'Riot Games',
	developer: 'Riot Games',
	release_date: '2020-06-02',
	freetogame_profile_url: 'https://www.freetogame.com/valorant'
  },
  {
	id: 467,
	title: 'Phantasy Star Online 2',
	thumbnail: 'https://www.freetogame.com/g/467/thumbnail.jpg',
	short_description: 'Welcome to ARKS, and elite task force searching dangerous planets for the corrupted Falspawn in Phantasy Star 2 Online, Sega’s popular, free-to-play sci-fi MMORPG.',
	game_url: 'https://www.freetogame.com/open/pso2',
	genre: 'MMORPG',
	platform: 'PC (Windows)',
	publisher: 'SEGA',
	developer: 'SEGA',
	release_date: '2020-05-27',
	freetogame_profile_url: 'https://www.freetogame.com/pso2'
  },
  {
	id: 452,
	title: 'Call Of Duty: Warzone',
	thumbnail: 'https://www.freetogame.com/g/452/thumbnail.jpg',
	short_description: 'A standalone free-to-play battle royale and modes accessible via Call of Duty: Modern Warfare.',
	game_url: 'https://www.freetogame.com/open/call-of-duty-warzone',
	genre: 'Shooter',
	platform: 'PC (Windows)',
	publisher: 'Activision',
	developer: 'Infinity Ward',
	release_date: '2020-03-10',
	freetogame_profile_url: 'https://www.freetogame.com/call-of-duty-warzone'
  },
  {
	id: 21,
	title: 'Destiny 2',
	thumbnail: 'https://www.freetogame.com/g/21/thumbnail.jpg',
	short_description: 'A free-to-play multiplayer Sci-Fi MMOFPS from Bungie.',
	game_url: 'https://www.freetogame.com/open/destiny-2',
	genre: 'Shooter',
	platform: 'PC (Windows)',
	publisher: 'Bungie',
	developer: 'Bungie',
	release_date: '2019-10-01',
	freetogame_profile_url: 'https://www.freetogame.com/destiny-2'
  },
  {
	id: 23,
	title: 'Apex Legends',
	thumbnail: 'https://www.freetogame.com/g/23/thumbnail.jpg',
	short_description: 'A free-to-play strategic battle royale game featuring 60-player matches and team-based play. ',
	game_url: 'https://www.freetogame.com/open/apex-legends',
	genre: 'Shooter',
	platform: 'PC (Windows)',
	publisher: 'Electronic Arts',
	developer: 'Electronic Arts',
	release_date: '2019-02-04',
	freetogame_profile_url: 'https://www.freetogame.com/apex-legends'
  },
  {
	id: 57,
	title: 'Fortnite',
	thumbnail: 'https://www.freetogame.com/g/57/thumbnail.jpg',
	short_description: "A free-to-play, standalone mode of Epic Game's Fortnite. ",
	game_url: 'https://www.freetogame.com/open/fortnite-battle-royale',
	genre: 'Shooter',
	platform: 'PC (Windows)',
	publisher: 'Epic Games',
	developer: 'Epic Games',
	release_date: '2017-09-26',
	freetogame_profile_url: 'https://www.freetogame.com/fortnite-battle-royale'
  },
  {
	id: 449,
	title: 'Albion Online',
	thumbnail: 'https://www.freetogame.com/g/449/thumbnail.jpg',
	short_description: 'A free-to-play cross-platform sandbox MMO developed and published by Sandbox Interactive GmbH. ',
	game_url: 'https://www.freetogame.com/open/albion-online',
	genre: 'MMORPG',
	platform: 'PC (Windows)',
	publisher: 'Sandbox Interactive GmbH',
	developer: 'Sandbox Interactive GmbH',
	release_date: '2017-07-17',
	freetogame_profile_url: 'https://www.freetogame.com/albion-online'
  },
  {
	id: 6,
	title: 'Blade and Soul',
	thumbnail: 'https://www.freetogame.com/g/6/thumbnail.jpg',
	short_description: 'A free-to-play martial arts MMORPG that tasks players with learning combination attacks.',
	game_url: 'https://www.freetogame.com/open/blade-and-soul',
	genre: 'MMORPG',
	platform: 'PC (Windows)',
	publisher: 'NCSoft',
	developer: 'NCSoft',
	release_date: '2016-01-19',
	freetogame_profile_url: 'https://www.freetogame.com/blade-and-soul'
  },
  {
	id: 212,
	title: 'Brawlhalla',
	thumbnail: 'https://www.freetogame.com/g/212/thumbnail.jpg',
	short_description: 'A free-to-play 2D platform fighter inspired by the Smash Bros.',
	game_url: 'https://www.freetogame.com/open/brawlhalla',
	genre: 'Fighting',
	platform: 'PC (Windows)',
	publisher: 'Blue Mammoth Games',
	developer: 'Blue Mammoth Games',
	release_date: '2015-11-03',
	freetogame_profile_url: 'https://www.freetogame.com/brawlhalla'
  },
  {
	id: 8,
	title: 'Trove',
	thumbnail: 'https://www.freetogame.com/g/8/thumbnail.jpg',
	short_description: 'A free to play Sandbox massively multiplayer online role-playing game! ',
	game_url: 'https://www.freetogame.com/open/trove',
	genre: 'MMORPG',
	platform: 'PC (Windows)',
	publisher: 'Trion Worlds',
	developer: 'Trion Worlds',
	release_date: '2015-07-09',
	freetogame_profile_url: 'https://www.freetogame.com/trove'
  },
  {
	id: 3,
	title: 'Warframe',
	thumbnail: 'https://www.freetogame.com/g/3/thumbnail.jpg',
	short_description: 'A cooperative free-to-play third person online action shooter set in an stunning sci-fi world. ',
	game_url: 'https://www.freetogame.com/open/warframe',
	genre: 'Shooter',
	platform: 'PC (Windows)',
	publisher: 'Digital Extremes',
	developer: 'Digital Extremes',
	release_date: '2013-03-25',
	freetogame_profile_url: 'https://www.freetogame.com/warframe'
  },
  {
	id: 13,
	title: 'Guild Wars 2',
	thumbnail: 'https://www.freetogame.com/g/13/thumbnail.jpg',
	short_description: "A free-to-play MMORPG, the follow-up to ArenaNet's popular Guild Wars. ",
	game_url: 'https://www.freetogame.com/open/guild-wars-2',
	genre: 'MMORPG',
	platform: 'PC (Windows)',
	publisher: 'NCsoft',
	developer: 'ArenaNet',
	release_date: '2012-08-28',
	freetogame_profile_url: 'https://www.freetogame.com/guild-wars-2'
  },
  {
	id: 350,
	title: 'Goodgame Empire',
	thumbnail: 'https://www.freetogame.com/g/350/thumbnail.jpg',
	short_description: 'A free to play medieval strategy browser game. Build you own castle and create a powerful army! ',
	game_url: 'https://www.freetogame.com/open/goodgame-empire',
	genre: 'Strategy',
	platform: 'Web Browser',
	publisher: 'Goodgame Studios',
	developer: 'Goodgame Studios',
	release_date: '2011-08-14',
	freetogame_profile_url: 'https://www.freetogame.com/goodgame-empire'
  },
  {
	id: 427,
	title: 'Drakensang Online',
	thumbnail: 'https://www.freetogame.com/g/427/thumbnail.jpg',
	short_description: 'A free to play browser-based top-down hack-and-slash 3D MMORPG similar to games in the Diablo series.',
	game_url: 'https://www.freetogame.com/open/drakensang-online',
	genre: 'MMORPG',
	platform: 'Web Browser',
	publisher: 'Bigpoint',
	developer: 'Bigpoint',
	release_date: '2011-08-08',
	freetogame_profile_url: 'https://www.freetogame.com/drakensang-online'
  },
  {
	id: 433,
	title: 'RuneScape',
	thumbnail: 'https://www.freetogame.com/g/433/thumbnail.jpg',
	short_description: 'A popular 3D browser MMORPG boasting a huge player base and 15 years of content.',
	game_url: 'https://www.freetogame.com/open/runescape',
	genre: 'MMORPG',
	platform: 'PC (Windows), Web Browser',
	publisher: 'Jagex',
	developer: 'Jagex',
	release_date: '2001-01-04',
	freetogame_profile_url: 'https://www.freetogame.com/runescape'
  },
  {
	id: 255,
	title: 'Stronghold Kingdoms',
	thumbnail: 'https://www.freetogame.com/g/255/thumbnail.jpg',
	short_description: 'A strategy based building/warfare game based on the long running Strongholds PC game series.',
	game_url: 'https://www.freetogame.com/open/stronghold-kingdoms',
	genre: 'Strategy',
	platform: 'Web Browser',
	publisher: 'FireFly Studios',
	developer: 'FireFly Studios',
	release_date: '2012-02-28',
	freetogame_profile_url: 'https://www.freetogame.com/stronghold-kingdoms'
  },
  {
	id: 606,
	title: 'Steel Hunters',
	thumbnail: 'https://www.freetogame.com/g/606/thumbnail.jpg',
	short_description: 'A post-apocalyptic extraction shooter with giant mechs.',
	game_url: 'https://www.freetogame.com/open/steel-hunters',
	genre: 'Shooter',
	platform: 'PC (Windows)',
	publisher: 'Wargaming ',
	developer: 'Wargaming',
	release_date: '2025-04-02',
	freetogame_profile_url: 'https://www.freetogame.com/steel-hunters'
  },
  {
	id: 603,
	title: 'War Robots: Frontiers',
	thumbnail: 'https://www.freetogame.com/g/603/thumbnail.jpg',
	short_description: 'A multiplayer mech game set in a planetary system light years from Earth.',
	game_url: 'https://www.freetogame.com/open/war-robots-frontiers',
	genre: 'Shooter',
	platform: 'PC (Windows)',
	publisher: 'My.games',
	developer: 'My.games',
	release_date: '2025-03-04',
	freetogame_profile_url: 'https://www.freetogame.com/war-robots-frontiers'
  },
  {
	id: 601,
	title: 'Delta Force',
	thumbnail: 'https://www.freetogame.com/g/601/thumbnail.jpg',
	short_description: 'A free-to-play team-based tactical shooter.',
	game_url: 'https://www.freetogame.com/open/delta-force',
	genre: 'Shooter',
	platform: 'PC (Windows)',
	publisher: 'TiMi Studio Group',
	developer: 'Team Jade',
	release_date: '2024-12-04',
	freetogame_profile_url: 'https://www.freetogame.com/delta-force'
  },
	{
		"id": 582,
		"title": "Tarisland",
		"thumbnail": "https://www.freetogame.com/g/582/thumbnail.jpg",
		"short_description": "A cross-platform MMORPG developed by Level Infinite and Published by Tencent.",
		"game_url": "https://www.freetogame.com/open/tarisland",
		"genre": "MMORPG",
		"platform": "PC (Windows)",
		"publisher": "Tencent",
		"developer": "Level Infinite",
		"release_date": "2024-06-22",
		"freetogame_profile_url": "https://www.freetogame.com/tarisland"
	  },
	  {
		"id": 540,
		"title": "Overwatch 2",
		"thumbnail": "https://www.freetogame.com/g/540/thumbnail.jpg",
		"short_description": "A hero-focused first-person team shooter from Blizzard Entertainment.",
		"game_url": "https://www.freetogame.com/open/overwatch-2",
		"genre": "Shooter",
		"platform": "PC (Windows)",
		"publisher": "Activision Blizzard",
		"developer": "Blizzard Entertainment",
		"release_date": "2022-10-04",
		"freetogame_profile_url": "https://www.freetogame.com/overwatch-2"
	  },
	  {
		"id": 516,
		"title": "PUBG: BATTLEGROUNDS",
		"thumbnail": "https://www.freetogame.com/g/516/thumbnail.jpg",
		"short_description": "Get into the action in one of the longest running battle royale games PUBG Battlegrounds.",
		"game_url": "https://www.freetogame.com/open/pubg",
		"genre": "Shooter",
		"platform": "PC (Windows)",
		"publisher": "KRAFTON, Inc.",
		"developer": "KRAFTON, Inc.",
		"release_date": "2022-01-12",
		"freetogame_profile_url": "https://www.freetogame.com/pubg"
	  },
	  {
		"id": 508,
		"title": "Enlisted",
		"thumbnail": "https://www.freetogame.com/g/508/thumbnail.jpg",
		"short_description": "Get ready to command your own World War II military squad in Gaijin and Darkflow Software’s MMO squad-based shooter Enlisted. ",
		"game_url": "https://www.freetogame.com/open/enlisted",
		"genre": "Shooter",
		"platform": "PC (Windows)",
		"publisher": "Gaijin Entertainment",
		"developer": "Darkflow Software",
		"release_date": "2021-04-08",
		"freetogame_profile_url": "https://www.freetogame.com/enlisted"
	  },
	  {
		"id": 345,
		"title": "Forge of Empires",
		"thumbnail": "https://www.freetogame.com/g/345/thumbnail.jpg",
		"short_description": "A free to play 2D browser-based online strategy game, become the leader and raise your city.",
		"game_url": "https://www.freetogame.com/open/forge-of-empires",
		"genre": "Strategy",
		"platform": "Web Browser",
		"publisher": "InnoGames",
		"developer": "InnoGames",
		"release_date": "2012-04-17",
		"freetogame_profile_url": "https://www.freetogame.com/forge-of-empires"
	  },
	  {
		"id": 604,
		"title": "FragPunk",
		"thumbnail": "https://www.freetogame.com/g/604/thumbnail.jpg",
		"short_description": "A free-to-play 5v5 hero shooter that uses cards to modify matches.",
		"game_url": "https://www.freetogame.com/open/fragpunk",
		"genre": "Shooter",
		"platform": "PC (Windows)",
		"publisher": "Bad Guitar Studio",
		"developer": "Bad Guitar Studio",
		"release_date": "2025-03-06",
		"freetogame_profile_url": "https://www.freetogame.com/fragpunk"
	  },
	  {
		id: 255,
		title: 'Stronghold Kingdoms',
		thumbnail: 'https://www.freetogame.com/g/255/thumbnail.jpg',
		short_description: 'A strategy based building/warfare game based on the long running Strongholds PC game series.',
		game_url: 'https://www.freetogame.com/open/stronghold-kingdoms',
		genre: 'Strategy',
		platform: 'Web Browser',
		publisher: 'FireFly Studios',
		developer: 'FireFly Studios',
		release_date: '2012-02-28',
		freetogame_profile_url: 'https://www.freetogame.com/stronghold-kingdoms'
	  },
	  {
		id: 606,
		title: 'Steel Hunters',
		thumbnail: 'https://www.freetogame.com/g/606/thumbnail.jpg',
		short_description: 'A post-apocalyptic extraction shooter with giant mechs.',
		game_url: 'https://www.freetogame.com/open/steel-hunters',
		genre: 'Shooter',
		platform: 'PC (Windows)',
		publisher: 'Wargaming ',
		developer: 'Wargaming',
		release_date: '2025-04-02',
		freetogame_profile_url: 'https://www.freetogame.com/steel-hunters'
	  },
	  {
		id: 603,
		title: 'War Robots: Frontiers',
		thumbnail: 'https://www.freetogame.com/g/603/thumbnail.jpg',
		short_description: 'A multiplayer mech game set in a planetary system light years from Earth.',
		game_url: 'https://www.freetogame.com/open/war-robots-frontiers',
		genre: 'Shooter',
		platform: 'PC (Windows)',
		publisher: 'My.games',
		developer: 'My.games',
		release_date: '2025-03-04',
		freetogame_profile_url: 'https://www.freetogame.com/war-robots-frontiers'
	  },
	  {
		id: 601,
		title: 'Delta Force',
		thumbnail: 'https://www.freetogame.com/g/601/thumbnail.jpg',
		short_description: 'A free-to-play team-based tactical shooter.',
		game_url: 'https://www.freetogame.com/open/delta-force',
		genre: 'Shooter',
		platform: 'PC (Windows)',
		publisher: 'TiMi Studio Group',
		developer: 'Team Jade',
		release_date: '2024-12-04',
		freetogame_profile_url: 'https://www.freetogame.com/delta-force'
	  },
	  {
		id: 597,
		title: 'Strinova',
		thumbnail: 'https://www.freetogame.com/g/597/thumbnail.jpg',
		short_description: 'A third-person tactical shooter that features the unique mechanic of allowing players to switch between three-dimensional and two-dimensional forms.',
		game_url: 'https://www.freetogame.com/open/strinova',
		genre: 'Shooter',
		platform: 'PC (Windows)',
		publisher: 'iDreamSky',
		developer: 'iDreamSky',
		release_date: '2024-11-21',
		freetogame_profile_url: 'https://www.freetogame.com/strinova'
	  },
	  {
		id: 598,
		title: 'SUPERVIVE',
		thumbnail: 'https://www.freetogame.com/g/598/thumbnail.jpg',
		short_description: 'Combine MOBAs, battle royales, and hero shooters into one fast paced game hand you have SUPERVIVE.',
		game_url: 'https://www.freetogame.com/open/supervive',
		genre: 'MOBA',
		platform: 'PC (Windows)',
		publisher: 'Theorycraft Games',
		developer: 'Theorycraft Games',
		release_date: '2024-11-20',
		freetogame_profile_url: 'https://www.freetogame.com/supervive'
	  },
	  {
		id: 592,
		title: 'Starborne: Frontiers',
		thumbnail: 'https://www.freetogame.com/g/592/thumbnail.jpg',
		short_description: 'A tactical autobattler set 400 years in the future.',
		game_url: 'https://www.freetogame.com/open/starborne-frontiers',
		genre: 'Strategy',
		platform: 'PC (Windows)',
		publisher: 'Solid Clouds hf.',
		developer: 'Solid Clouds hf.',
		release_date: '2024-10-14',
		freetogame_profile_url: 'https://www.freetogame.com/starborne-frontiers'
	  },
	  {
		id: 593,
		title: 'Return Alive',
		thumbnail: 'https://www.freetogame.com/g/593/thumbnail.jpg',
		short_description: 'A free-to-play top-down tactical shooter.',
		game_url: 'https://www.freetogame.com/open/return-alive',
		genre: 'Shooter',
		platform: 'PC (Windows)',
		publisher: 'KOG',
		developer: 'KOG',
		release_date: '2024-10-23',
		freetogame_profile_url: 'https://www.freetogame.com/return-alive'
	  },
	  {
		id: 587,
		title: 'Spectre Divide',
		thumbnail: 'https://www.freetogame.com/g/587/thumbnail.jpg',
		short_description: 'A 3v3 tactical shooter developed and published by Mountaintop Studios in partnership with former pro gamer shroud,',
		game_url: 'https://www.freetogame.com/open/spectre-divide',
		genre: 'Shooter',
		platform: 'PC (Windows)',
		publisher: 'Mountaintop Studios',
		developer: 'Mountaintop Studios',
		release_date: '2024-09-03',
		freetogame_profile_url: 'https://www.freetogame.com/spectre-divide'
	  },
	  {
		id: 588,
		title: 'Vigor',
		thumbnail: 'https://www.freetogame.com/g/588/thumbnail.jpg',
		short_description: 'A free-to-play looter shooter from the developers of Operation Flashpoint and the Arma series.',
		game_url: 'https://www.freetogame.com/open/vigor',
		genre: 'Shooter',
		platform: 'PC (Windows)',
		publisher: 'Bohemia Interactive ',
		developer: 'Bohemia Interactive',
		release_date: '2024-09-18',
		freetogame_profile_url: 'https://www.freetogame.com/vigor'
	  },
	  {
		id: 602,
		title: 'Smite 2',
		thumbnail: 'https://www.freetogame.com/g/602/thumbnail.jpg',
		short_description: 'The free-to-play Unreal Engine 5-powered sequel to the popular third-person MOBA',
		game_url: 'https://www.freetogame.com/open/smite-2',
		genre: 'MOBA',
		platform: 'PC (Windows)',
		publisher: 'Hi-Rez Studios',
		developer: 'Titan Forge Games',
		release_date: '2024-08-27',
		freetogame_profile_url: 'https://www.freetogame.com/smite-2'
	  },
	  {
		id: 583,
		title: 'The First Descendant',
		thumbnail: 'https://www.freetogame.com/g/583/thumbnail.jpg',
		short_description: 'A free-to-play third-person co-op looter shooter developed and published by Nexon.',
		game_url: 'https://www.freetogame.com/open/the-first-descendant',
		genre: 'Shooter',
		platform: 'PC (Windows)',
		publisher: 'Nexon',
		developer: 'Nexon Games Co., Ltd.',
		release_date: '2024-07-02',
		freetogame_profile_url: 'https://www.freetogame.com/the-first-descendant'
	  },
	  {
		id: 584,
		title: 'Once Human',
		thumbnail: 'https://www.freetogame.com/g/584/thumbnail.jpg',
		short_description: 'A post-apocalyptic open-world survival game from Starry Studio.',
		game_url: 'https://www.freetogame.com/open/once-human',
		genre: 'Shooter',
		platform: 'PC (Windows)',
		publisher: 'Starry Studio',
		developer: 'Starry Studio',
		release_date: '2024-07-09',
		freetogame_profile_url: 'https://www.freetogame.com/once-human'
	  },
	  {
		id: 586,
		title: 'Stormgate',
		thumbnail: 'https://www.freetogame.com/g/586/thumbnail.jpg',
		short_description: 'A free-to-play science fantasy real-time strategy game in which humans and robots defend Earth from alien forces.',
		game_url: 'https://www.freetogame.com/open/stormgate',
		genre: 'Strategy',
		platform: 'PC (Windows)',
		publisher: 'Frost Giant Studios',
		developer: 'Frost Giant Studios',
		release_date: '2024-07-30',
		freetogame_profile_url: 'https://www.freetogame.com/stormgate'
	  },
	  {
		id: 596,
		title: 'Fractured Online',
		thumbnail: 'https://www.freetogame.com/g/596/thumbnail.jpg',
		short_description: 'A free-to-play open-world sandbox MMORPG from developer and publisher Dynamight Studios',
		game_url: 'https://www.freetogame.com/open/fractured-online',
		genre: 'MMORPG',
		platform: 'PC (Windows)',
		publisher: 'Dynamight Studios',
		developer: 'Dynamight Studios',
		release_date: '2024-07-24',
		freetogame_profile_url: 'https://www.freetogame.com/fractured-online'
	  },
	  {
		id: 591,
		title: 'Battle Crush',
		thumbnail: 'https://www.freetogame.com/g/591/thumbnail.jpg',
		short_description: 'An action brawler for up to 30 players.',
		game_url: 'https://www.freetogame.com/open/battle-crush',
		genre: 'Battle Royale',
		platform: 'PC (Windows)',
		publisher: 'NCSoft',
		developer: 'NCSoft',
		release_date: '2024-06-27',
		freetogame_profile_url: 'https://www.freetogame.com/battle-crush'
	  },
	  {
		id: 580,
		title: 'Screenplay CCG',
		thumbnail: 'https://www.freetogame.com/g/580/thumbnail.jpg',
		short_description: 'A collectible card game inspired by movie making.',
		game_url: 'https://www.freetogame.com/open/screenplay',
		genre: 'Card Game',
		platform: 'PC (Windows)',
		publisher: 'Comico Games',
		developer: 'Comico Games',
		release_date: '2024-05-13',
		freetogame_profile_url: 'https://www.freetogame.com/screenplay'
	  },
	  {
		id: 585,
		title: 'SolForge Fusion',
		thumbnail: 'https://www.freetogame.com/g/585/thumbnail.jpg',
		short_description: 'A card-battling game in which each card levels up and becomes more powerful.',
		game_url: 'https://www.freetogame.com/open/solforge-fusion',
		genre: 'Card Game',
		platform: 'PC (Windows)',
		publisher: 'Stone Blade Entertainment',
		developer: 'Richard Garfield, Justin Gary',
		release_date: '2024-04-16',
		freetogame_profile_url: 'https://www.freetogame.com/solforge-fusion'
	  },
	  {
		id: 589,
		title: 'Sky: Children of the Light',
		thumbnail: 'https://www.freetogame.com/g/589/thumbnail.jpg',
		short_description: 'A cozy free-to-play MMORPG from thatgamecompany.',
		game_url: 'https://www.freetogame.com/open/sky-children-of-the-light',
		genre: 'MMORPG',
		platform: 'PC (Windows)',
		publisher: 'thatgamecompany',
		developer: 'thatgamecompany',
		release_date: '2024-04-10',
		freetogame_profile_url: 'https://www.freetogame.com/sky-children-of-the-light'
	  },
	  {
		id: 578,
		title: 'Predecessor',
		thumbnail: 'https://www.freetogame.com/g/578/thumbnail.jpg',
		short_description: 'A free-to-play MOBA shooter developed and published by Omeda Studios.',
		game_url: 'https://www.freetogame.com/open/predecessor',
		genre: 'MOBA',
		platform: 'PC (Windows)',
		publisher: 'Omeda Studios',
		developer: 'Omeda Studios',
		release_date: '2024-03-28',
		freetogame_profile_url: 'https://www.freetogame.com/predecessor'
	  },
	  {
		id: 579,
		title: 'Project Apidom',
		thumbnail: 'https://www.freetogame.com/g/579/thumbnail.jpg',
		short_description: 'A free-to-play apocalyptic extraction RPG with MOBA-like combat.',
		game_url: 'https://www.freetogame.com/open/project-apidom',
		genre: 'MOBA',
		platform: 'PC (Windows)',
		publisher: 'Breach.gg, RedTigerPro',
		developer: 'Breach.gg',
		release_date: '2024-03-29',
		freetogame_profile_url: 'https://www.freetogame.com/project-apidom'
	  },
	  {
		id: 572,
		title: 'Ravendawn',
		thumbnail: 'https://www.freetogame.com/g/572/thumbnail.jpg',
		short_description: 'A 2D top-down MMORPG featuring homesteading and building mechanics.',
		game_url: 'https://www.freetogame.com/open/ravendawn',
		genre: 'MMORPG',
		platform: 'PC (Windows)',
		publisher: 'Tavernlight Games',
		developer: 'Tavernlight Games',
		release_date: '2024-01-16',
		freetogame_profile_url: 'https://www.freetogame.com/ravendawn'
	  },
	  {
		id: 62,
		title: 'Kritika: Zero',
		thumbnail: 'https://www.freetogame.com/g/62/thumbnail.jpg',
		short_description: 'A free-to-play hack-and-slash MMORPG with both a single-player adventure combat from Valofe. ',
		game_url: 'https://www.freetogame.com/open/kritika',
		genre: 'MMORPG',
		platform: 'PC (Windows)',
		publisher: 'Valofe',
		developer: 'Valofe',
		release_date: '2024-01-25',
		freetogame_profile_url: 'https://www.freetogame.com/kritika'
	  },
	  {
		id: 575,
		title: 'One Punch Man: World',
		thumbnail: 'https://www.freetogame.com/g/575/thumbnail.jpg',
		short_description: 'A free-to-play multiplayer 3D action game from Crunchyroll Games.',
		game_url: 'https://www.freetogame.com/open/one-punch-man-world',
		genre: 'Action Game',
		platform: 'PC (Windows)',
		publisher: 'Perfect World Games',
		developer: 'Crunchyroll',
		release_date: '2024-01-31',
		freetogame_profile_url: 'https://www.freetogame.com/one-punch-man-world'
	  },
	  {
		id: 576,
		title: 'Battle Teams 2',
		thumbnail: 'https://www.freetogame.com/g/576/thumbnail.jpg',
		short_description: 'A multiplayer tactical shooter with an Eastern aesthetic.',
		game_url: 'https://www.freetogame.com/open/battle-teams-2',
		genre: 'Shooter',
		platform: 'PC (Windows)',
		publisher: 'Wizard Games Global',
		developer: 'Wizard Games Global',
		release_date: '2024-01-31',
		freetogame_profile_url: 'https://www.freetogame.com/battle-teams-2'
	  },
	  {
		id: 570,
		title: 'The Finals',
		thumbnail: 'https://www.freetogame.com/g/570/thumbnail.jpg',
		short_description: 'A game-show style PvP shooter from Embark Studios.',
		game_url: 'https://www.freetogame.com/open/the-finals',
		genre: 'Shooter',
		platform: 'PC (Windows)',
		publisher: 'Embark Studios',
		developer: 'Embark Studios',
		release_date: '2023-12-07',
		freetogame_profile_url: 'https://www.freetogame.com/the-finals'
	  },
]

dataGames.forEach((game) => {

const cardGame = document.createElement("div");

cardGame.innerHTML = `<div class="producto">
                <!-- <a href="producto.html"> -->
                    <img class="producto__imagen" src="${game.thumbnail}" alt="imagen">
                    <div class="productp__informacion">
                        <p class="producto__nombre">${game.title}</p>
                        <p class="producto__descripcion">${game.short_description}</p>
                        <p class="producto__descripcion">Plataforma: ${game.platform}</p>
                        <p class="producto__descripcion">Genero: ${game.genre}</p>
					<div class="enlace_juego">
                             <a class="enlace_juego" href="${game.game_url}">Link del juego</a>
                      </div>
					 
                    </div>
                </a>
            </div> `;
grid.append(cardGame);
});
